### ISSUE TITLE
PyPI release of generate-iconset?

### ISSUE THREAD

**Issue by glyph** [retifrav/python-scripts#2]
I'd love to put this into a `dev-requirements.txt` in a few places :-).

**Comment by retifrav** [comment]
It didn't occur to me, that this script might deserve its own package at PyPI, but sure, I could do that.
Worst case, they'll delete it as unworthy, and that's how we'll know :)

**Comment by glyph** [comment]
@retifrav There's no arbitration panel on PyPI for judging "worthiness" :-).  If it's not malware, it's fine to put it up there.

Thanks!

**Comment by retifrav** [comment]
Done: <https://pypi.org/project/generate-iconset/>. It's a proper CLI tool now.
Moved it to a [new repository](https://github.com/retifrav/generate-iconset) for the ease of maintenance.

Also fixed incorrect sizes generation - it was messed up a bit, and I never noticed. But `iconutil` didn't complain either.
Plus added some more CLI arguments for convenience (*run with `--help` for details*).
