### ISSUE TITLE
https://github.com/HelpSeeker/CoubDownloader/issues/11

### ISSUE THREAD

**Issue by AdventurerRussia** [retifrav/python-scripts#3]
after my topic was closed, I asked a programmer friend to write me a script, 3 weeks ago coub announced the sale and our Russian guys made a program that pumps out coub from all sections, even from the bookmarks section. At the same time, it immediately loops them in maximum quality and allows you to download a list of direct links separately. I personally asked them about this functionality.
the user token can be specified in the settings.
https://coubassistant.com/apps/windows/coubarchiver/downloads/coub_archiver_v5b.exe

**Comment by retifrav** [comment]
It might be useful for someone, but I've already downloaded all my Coub likes the way I described in the [original CoubDownloader issue](https://github.com/HelpSeeker/CoubDownloader/issues/11#issuecomment-1001063588). Also I'm not brave enough to run arbitrary executables from the internet (*not to mention that I am on Mac OS and don't have a Windows machine*).

Either way, what you posted here is not an issue of this repository, is it. Would be better if you posted it in the original one.

**Comment by AdventurerRussia** [comment]
I have not found any other way to write and share with you other than to create a theme here.
And your script does not allow you to download likes from the bookmarks section. I decided that it might be useful to you

**Comment by retifrav** [comment]
Your original question back there was about likes, you didn't mention bookmarks (*I don't even know what that is*).

**Comment by AdventurerRussia** [comment]
https://coub.com/bookmarks

**Comment by retifrav** [comment]
Like I said, your question was about likes, and I needed to get only likes, and so my script doesn't save anything but likes.
